var PREGUNTAS = {
    disc: {
        nombre: "Perfil DISC - Evaluaci\u00f3n Comportamental Asistente Contable",
        descripcion: "Seleccione la opci\u00f3n que mejor lo describe. No hay respuestas correctas o incorrectas.",
        tiempo: 1200,
        preguntas: [
            { id: 1, dimensi: "D", pregunta: "Cuando detecto un error material en la conciliaci\u00f3n bancaria que retrasa el cierre, prefiero:", opcionA: "Resolverlo de inmediato tomando control de la situaci\u00f3n y corrigiendo el registro", opcionB: "Reportarlo a mi superior y esperar su instrucci\u00f3n antes de actuar", pesoA: 1, pesoB: 0 },
            { id: 2, dimensi: "D", pregunta: "Ante un vencimiento cr\u00edtico de declaraci\u00f3n de impuestos que se aproxima, mi reacci\u00f3n es:", opcionA: "Organizar el trabajo y exigirme cumplir el plazo con prioridad absoluta", opcionB: "Seguir el ritmo habitual confiando en que se completar\u00e1 a tiempo", pesoA: 1, pesoB: 0 },
            { id: 3, dimensi: "D", pregunta: "Cuando una factura no cuadra con el soporte del proveedor y hay presi\u00f3n por pagar, yo:", opcionA: "Detengo el pago y exijo la correcci\u00f3n del documento antes de continuar", opcionB: "Prefiero consultar antes de tomar una decisi\u00f3n que pueda afectar la relaci\u00f3n", pesoA: 1, pesoB: 0 },
            { id: 4, dimensi: "D", pregunta: "En la gesti\u00f3n del cierre contable mensual, prefiero:", opcionA: "Marcar objetivos claros, asignar tareas y exigir resultados dentro de los plazos", opcionB: "Avanzar gradualmente asegurando que cada proceso quede bien documentado", pesoA: 1, pesoB: 0 },
            { id: 5, dimensi: "D", pregunta: "Cuando identifico una diferencia de inventario que no se explica f\u00e1cilmente, yo:", opcionA: "Investigo directamente y tomo acci\u00f3n hasta resolverla", opcionB: "Espero que el \u00e1rea responsable presente su an\u00e1lisis", pesoA: 1, pesoB: 0 },
            { id: 6, dimensi: "D", pregunta: "En un entorno de alta presi\u00f3n con m\u00faltiples cierres simult\u00e1neos, prefiero:", opcionA: "Acelerar el ritmo y priorizar yo mismo las tareas m\u00e1s cr\u00edticas", opcionB: "Mantener un ritmo met\u00f3dico para no comprometer la exactitud", pesoA: 1, pesoB: 0 },
            { id: 7, dimensi: "I", pregunta: "Al presentar un informe financiero a gerencia, prefiero:", opcionA: "Explicarlo con claridad, destacando los puntos clave y generando confianza", opcionB: "Entregar el informe por escrito con los datos t\u00e9cnicos completos", pesoA: 1, pesoB: 0 },
            { id: 8, dimensi: "I", pregunta: "Cuando debo coordinar con auditores externos la revisi\u00f3n de los soportes contables:", opcionA: "Me comunico proactivamente y facilito la informaci\u00f3n con buena disposici\u00f3n", opcionB: "Entrego lo solicitado de forma ordenada sin extender la interacci\u00f3n", pesoA: 1, pesoB: 0 },
            { id: 9, dimensi: "I", pregunta: "En el proceso de cobro de cartera vencida, prefiero:", opcionA: "Llamar a los clientes, negociar plazos y construir relaciones de cobro efectivas", opcionB: "Enviar recordatorios formales y reportes de cartera por escrito", pesoA: 1, pesoB: 0 },
            { id: 10, dimensi: "I", pregunta: "Cuando un proveedor reclama por un pago pendiente, mi enfoque es:", opcionA: "Atenderlo con empat\u00eda, explicar el estado del pago y coordinar la soluci\u00f3n", opcionB: "Remitirme a los procedimientos internos y al sistema de cuentas por pagar", pesoA: 1, pesoB: 0 },
            { id: 11, dimensi: "I", pregunta: "Al explicar a un \u00e1rea operativa una diferencia contable que le afecta, prefiero:", opcionA: "Dialogar y asegurarme de que comprendan el origen del ajuste", opcionB: "Enviar el detalle del ajuste por escrito para su revisi\u00f3n", pesoA: 1, pesoB: 0 },
            { id: 12, dimensi: "I", pregunta: "En una reuni\u00f3n de revisi\u00f3n de cierre con el equipo contable, prefiero:", opcionA: "Compartir los hallazgos y motivar al equipo a aportar soluciones", opcionB: "Presentar los datos objetivos y validar los saldos uno a uno", pesoA: 1, pesoB: 0 },
            { id: 13, dimensi: "S", pregunta: "En la causaci\u00f3n diaria de facturas de compra y venta, prefiero:", opcionA: "Registrarlas de forma continua y disciplinada apenas llegan", opcionB: "Acumularlas y causarlas en bloques cuando haya espacio", pesoA: 1, pesoB: 0 },
            { id: 14, dimensi: "S", pregunta: "Cuando hay cambios frecuentes en la normativa tributaria, prefiero:", opcionA: "Mantener una rutina de actualizaci\u00f3n y control de cambios peri\u00f3dica", opcionB: "Adaptarme a cada cambio seg\u00fan su urgencia e impacto", pesoA: 1, pesoB: 0 },
            { id: 15, dimensi: "S", pregunta: "En la liquidaci\u00f3n de n\u00f3mina mensual, prefiero:", opcionA: "Seguir un procedimiento estandarizado y verificarlo siempre en el mismo orden", opcionB: "Revisar los casos at\u00edpicos y ajustar el proceso seg\u00fan la situaci\u00f3n", pesoA: 1, pesoB: 0 },
            { id: 16, dimensi: "S", pregunta: "Cuando el proceso contable opera de forma estable y sin novedades:", opcionA: "Aprovecho para mejorar la documentaci\u00f3n, archivo y controles", opcionB: "Busco nuevas tareas o mejoras de proceso para variar", pesoA: 1, pesoB: 0 },
            { id: 17, dimensi: "S", pregunta: "En el seguimiento de los plazos de entrega de obligaciones a la DIAN, prefiero:", opcionA: "Llevar un control met\u00f3dico y anticiparme a cada vencimiento", opcionB: "Atender cada vencimiento cuando se acerca la fecha l\u00edmite", pesoA: 1, pesoB: 0 },
            { id: 18, dimensi: "S", pregunta: "Cuando recibo una solicitud de informaci\u00f3n contable incompleta, prefiero:", opcionA: "Solicitar los datos faltantes y esperar la informaci\u00f3n completa antes de procesar", opcionB: "Procesar con lo disponible para no retrasar la solicitud", pesoA: 1, pesoB: 0 },
            { id: 19, dimensi: "C", pregunta: "Al elaborar una conciliaci\u00f3n bancaria, prefiero:", opcionA: "Verificar cada partida, fecha y valor antes de dar por conciliado", opcionB: "Revisar los totales y los movimientos m\u00e1s significativos", pesoA: 1, pesoB: 0 },
            { id: 20, dimensi: "C", pregunta: "Frente a un requisito tributario nuevo que aplica a la empresa:", opcionA: "Estudio la norma a fondo y verifico el cumplimiento de cada aspecto", opcionB: "Identifico los aspectos principales y ajusto lo necesario", pesoA: 1, pesoB: 0 },
            { id: 21, dimensi: "C", pregunta: "Al registrar una operaci\u00f3n en el software contable, prefiero:", opcionA: "Verificar el plan de cuentas, el tercero y el valor antes de guardar", opcionB: "Registrar la informaci\u00f3n principal y revisarla al finalizar el d\u00eda", pesoA: 1, pesoB: 0 },
            { id: 22, dimensi: "C", pregunta: "En el manejo de la informaci\u00f3n confidencial de la empresa (n\u00f3mina, estados financieros), prefiero:", opcionA: "Seguir protocolos estrictos de confidencialidad y control de acceso", opcionB: "Confiar en la discreci\u00f3n del equipo y los sistemas establecidos", pesoA: 1, pesoB: 0 },
            { id: 23, dimensi: "C", pregunta: "Al archivar los soportes de contabilidad para auditor\u00eda, prefiero:", opcionA: "Organizarlos con un sistema claro por periodo, cuenta y tipo de documento", opcionB: "Archivarlos en orden cronol\u00f3gico para localizarlos r\u00e1pidamente", pesoA: 1, pesoB: 0 },
            { id: 24, dimensi: "C", pregunta: "Cuando encuentro una inconsistencia entre el sistema y los soportes f\u00edsicos, prefiero:", opcionA: "Investigar hasta encontrar la causa y corregir el registro en su origen", opcionB: "Se\u00f1alar la inconsistencia y solicitar la correcci\u00f3n al responsable", pesoA: 1, pesoB: 0 }
        ]
    },
    tecnico: {
        nombre: "Evaluaci\u00f3n T\u00e9cnica - Asistente Contable",
        descripcion: "Eval\u00faa tus conocimientos en causaci\u00f3n, facturaci\u00f3n electr\u00f3nica, NIIF, normatividad tributaria, n\u00f3mina, conciliaci\u00f3n y Excel.",
        tiempo: 1440,
        preguntas: [
            { id: 1, categoria: "Facturaci\u00f3n Electr\u00f3nica", pregunta: "Para que una factura electr\u00f3nica de venta a cr\u00e9dito sea procedente como costo, deducci\u00f3n en la declaraci\u00f3n de renta o impuesto descontable en IVA ante la DIAN, \u00bfqu\u00e9 requisito procedimental obligatorio debe verificar el Asistente Contable en el sistema RADIAN / WS DIAN?", opciones: ["Que la factura est\u00e9 impresa y firmada digitalmente por el representante legal del proveedor.", "La existencia de los tres eventos electr\u00f3nicos obligatorios: Acuse de recibo de la factura, Recibo del bien o servicio, y la Aceptaci\u00f3n expl\u00edcita (o t\u00e1cita pasados 3 d\u00edas h\u00e1biles).", "La recepci\u00f3n del mensaje electr\u00f3nico del XML y la confirmaci\u00f3n de la causaci\u00f3n en el software contable interno.", "Que la factura cuente \u00fanicamente con el c\u00f3digo CUFE v\u00e1lido y el env\u00edo del archivo PDF al correo corporativo."], correcta: 1 },
            { id: 2, categoria: "Normatividad Tributaria", pregunta: "Una empresa adquiere un servicio de mantenimiento de maquinaria por $15.000.000 con un proveedor no obligado a expedir factura electr\u00f3nica. \u00bfCu\u00e1l es el soporte v\u00e1lido exigido por la normatividad tributaria colombiana para la causaci\u00f3n y deducci\u00f3n del gasto?", opciones: ["La transmisi\u00f3n electr\u00f3nica a la DIAN del 'Documento Soporte en adquisiciones efectuadas a sujetos no obligados a expedir factura de venta o documento equivalente'.", "Una cuenta de cobro en formato PDF firmada por el prestador con copia del RUT actualizado.", "Un comprobante de egreso firmado por el proveedor junto con la planilla de seguridad social como independiente.", "Una nota de contabilidad interna firmada por el Contador P\u00fablico de la compa\u00f1\u00eda."], correcta: 0 },
            { id: 3, categoria: "NIIF para PYMES", pregunta: "Bajo NIIF para PYMES (Secci\u00f3n 11 - Instrumentos Financieros), si una cuenta por cobrar a clientes presenta una mora superior a 180 d\u00edas sin gesti\u00f3n efectiva de cobro y existe evidencia objetiva de deterioro de valor, \u00bfcu\u00e1l es el registro contable correcto que debe realizar el Asistente?", opciones: ["Acreditar directamente la cuenta de clientes (1305) y debitar la cuenta de p\u00e9rdida por baja en cuentas.", "Generar una Nota Cr\u00e9dito electr\u00f3nica en el sistema para anular la factura de venta original.", "Mantener el activo intacto hasta que un juez declare la insolvencia del cliente.", "Debitar la cuenta de gasto por deterioro (5199 / 5299) y acreditar la cuenta correctora de activo por deterioro acumulado (1399)."], correcta: 3 },
            { id: 4, categoria: "NIIF para PYMES", pregunta: "Una compa\u00f1\u00eda realiza un pago anticipado del 40% a un proveedor para la fabricaci\u00f3n de un activo fijo que ser\u00e1 entregado en 3 meses. \u00bfC\u00f3mo debe causar el Asistente Contable dicho desembolso inicialmente?", opciones: ["Debitar la cuenta de Gasto por compras de activos (5135) y acreditar Bancos (1110).", "Debitar la cuenta de Propiedad, Planta y Equipo (1524) por el valor total del contrato y acreditar Pasivo por Pagar (2335).", "Debitar la cuenta de Activo por Anticipo a Proveedores / Avances entregados (1330) y acreditar Bancos (1110).", "Debitar la cuenta de Inventarios en Tr\u00e1nsito (1435) y acreditar Costos por Pagar (2205)."], correcta: 2 },
            { id: 5, categoria: "Normatividad Tributaria", pregunta: "Se realiza una compra de mercanc\u00edas para la venta a un proveedor perteneciente al R\u00e9gimen Ordinario (Declarante de Renta) por valor de $2.500.000 antes de IVA. Sabiendo que la base m\u00ednima para compras es de 27 UVT (asumiendo 1 UVT = $49.799 = $1.344.573), \u00bfcu\u00e1les son las retenciones aplicables en la causaci\u00f3n?", opciones: ["Aplica Retenci\u00f3n en la fuente por compras del 2.5% y ReteICA seg\u00fan la tarifa municipal aplicable.", "No aplica ninguna retenci\u00f3n en la fuente por estar por debajo de la base m\u00ednima de 50 UVT.", "Aplica Retenci\u00f3n en la fuente por compras del 3.5% (por no declarante) y ReteIVA del 15%.", "Aplica \u00fanicamente Autorretenci\u00f3n Especial a t\u00edtulo de Renta a favor del comprador."], correcta: 0 },
            { id: 6, categoria: "Normatividad Tributaria", pregunta: "Una empresa que genera simult\u00e1neamente ingresos gravados con IVA al 19% e ingresos excluidos de IVA adquiere insumos operativos de uso com\u00fan para ambas actividades por $10.000.000 + IVA ($1.900.000). \u00bfC\u00f3mo debe tratar el Asistente Contable el IVA pagado en esta compra seg\u00fan el Estatuto Tributario (Art. 490)?", opciones: ["Registrar el 100% del IVA como descontable en la cuenta 2408.", "Aplicar el procedimiento de prorrateo de IVA para determinar qu\u00e9 proporci\u00f3n es descontable (2408) y cu\u00e1l se lleva como mayor valor del costo o gasto.", "Tratar el 100% del IVA como mayor valor del gasto/costo sin derecho a descuento.", "Solicitar la devoluci\u00f3n inmediata del IVA a la DIAN mediante formulario de compensaci\u00f3n."], correcta: 1 },
            { id: 7, categoria: "Normatividad Tributaria", pregunta: "Un proveedor con sede y matr\u00edcula mercantil exclusivamente en Medell\u00edn presta un servicio de mantenimiento preventivo de equipos en las instalaciones de la empresa ubicadas en Cartagena. Al causar la factura, \u00bfbajo qu\u00e9 criterio territorial debe practicarse la Retenci\u00f3n del Impuesto de Industria y Comercio (ReteICA)?", opciones: ["Se aplica la tarifa de ReteICA del municipio de Medell\u00edn, por ser la sede principal del proveedor.", "No se practica ReteICA por tratarse de un servicio intermunicipal.", "Se aplica la tarifa de ReteICA vigente en el municipio de Cartagena, por ser el lugar donde se ejecut\u00f3 f\u00edsicamente la prestaci\u00f3n del servicio.", "Se practica ReteICA \u00fanicamente si el proveedor es Gran Contribuyente designado por la DIAN."], correcta: 2 },
            { id: 8, categoria: "Normatividad Tributaria", pregunta: "En la causaci\u00f3n de la Autorretenci\u00f3n Especial a t\u00edtulo de Renta (Decreto 2201 de 2016 y sus modificaciones) para una empresa beneficiaria de la exoneraci\u00f3n de aportes del Art. 114-1 del E.T., \u00bfcu\u00e1l es el registro contable correcto que debe efectuar el Asistente sobre una venta de servicios de $20.000.000?", opciones: ["Debitar Retenci\u00f3n en la fuente por pagar (2365) y acreditar Ingresos operacionales (4135).", "Debitar Gasto impuesto de renta (5115) y acreditar Impuestos grav\u00e1menes y tasas (2404).", "Acreditar Retenci\u00f3n a t\u00edtulo de IVA (2408) y debitar Bancos (1110).", "Debitar Autorretenciones por cobrar / Anticipo de impuestos (1355) y acreditar Autorretenciones por pagar (2365) por la tarifa CIIU correspondiente."], correcta: 3 },
            { id: 9, categoria: "Normatividad Laboral", pregunta: "Un empleado con un sueldo b\u00e1sico de $3.000.000 deveng\u00f3 en el mes $1.500.000 adicionales por concepto de auxilios de mera liberalidad no constitutivos de salario. Seg\u00fan la Ley 1393 de 2010 (Art. 30), \u00bfcu\u00e1l es el Ingreso Base de Cotizaci\u00f3n (IBC) para el pago de Seguridad Social (Salud, Pensi\u00f3n y ARL)?", opciones: ["$3.000.000 (\u00danicamente el salario b\u00e1sico pactado).", "$3.300.000 (Salario b\u00e1sico m\u00e1s el exceso de los pagos no salariales que superen el 40% del total devengado).", "$4.500.000 (El 100% de la totalidad de lo devengado).", "$1.800.000 (Equivalente al 40% de la remuneraci\u00f3n total)."], correcta: 1 },
            { id: 10, categoria: "Normatividad Laboral", pregunta: "Al liquidar la n\u00f3mina mensual y sus respectivas provisiones de prestaciones sociales, \u00bfcu\u00e1l de los siguientes conceptos DEBE incluirse en la base de c\u00e1lculo de la Prima de Servicios y de las Cesant\u00edas, pero EXCLUIRSE de la base para Vacaciones?", opciones: ["Horas extras y recargos nocturnos.", "Comisiones por ventas.", "Auxilio de Transporte legal.", "Bonificaciones habituales constitutivas de salario."], correcta: 2 },
            { id: 11, categoria: "Normatividad Laboral", pregunta: "Una persona jur\u00eddica del r\u00e9gimen ordinario responsable del impuesto sobre la renta liquida la seguridad social (PILA) de sus trabajadores cuyos devengados individuales no superan los 10 SMMLV. \u00bfDe qu\u00e9 aportes patronales se encuentra exonerada de conformidad con el Art. 114-1 del Estatuto Tributario?", opciones: ["Exonerada de los aportes patronales a Salud (8.5%), SENA (2%) e ICBF (3%).", "Exonerada del aporte patronal a Pensi\u00f3n (12%) y ARL.", "Exonerada del pago de Cajas de Compensaci\u00f3n Familiar (4%) y Fondo de Solidaridad Pensional.", "Exonerada del 100% de los aportes a la planilla PILA."], correcta: 0 },
            { id: 12, categoria: "Normatividad Laboral", pregunta: "Un trabajador presenta una incapacidad por enfermedad general (origen com\u00fan) de 8 d\u00edas de duraci\u00f3n. \u00bfC\u00f3mo se distribuye la responsabilidad del pago y la causaci\u00f3n de dicha incapacidad durante los primeros d\u00edas?", opciones: ["La EPS paga el 100% de la incapacidad desde el primer d\u00eda de emisi\u00f3n del certificado.", "Los 8 d\u00edas son asumidos directamente y en su totalidad por la empresa como gasto no deducible.", "La ARL reconoce el 100% del IBC desde el d\u00eda 1 por tratarse de incapacidad temporal.", "Los primeros 2 d\u00edas los asume el empleador al 100% o 66.67% (seg\u00fan pol\u00edtica legal no inferior al SMMLV), y del d\u00eda 3 al 8 los asume la EPS al 66.67%."], correcta: 3 },
            { id: 13, categoria: "Conciliaci\u00f3n Bancaria", pregunta: "Durante el proceso de conciliaci\u00f3n bancaria al cierre de mes, el Asistente observa una consignaci\u00f3n en el extracto bancario por valor de $4.500.000 que no cuenta con soporte ni identificaci\u00f3n del cliente en la contabilidad. \u00bfCu\u00e1l es la conducta contable adecuada?", opciones: ["Acreditar directamente la cuenta de Ingresos Diversos (4295) para cuadrar la conciliaci\u00f3n bancaria.", "Debitar la cuenta Bancos (1110) y acreditar una cuenta de Pasivo (2805 / 2705 - Cr\u00e9ditos de clientes por clasificar / Anticipos) mientras se identifica el origen del recurso.", "No registrar nada en la contabilidad hasta que el cliente llame a reportar el pago.", "Registrar un menor valor en la cuenta de Gastos Bancarios (5305)."], correcta: 1 },
            { id: 14, categoria: "Conciliaci\u00f3n Bancaria", pregunta: "Una empresa adquiere mercanc\u00eda a cr\u00e9dito por USD $10.000 a una TRM de $3.900 COP/USD. Al cierre del mes, la TRM oficial de la Superintendencia Financiera sube a $4.100 COP/USD y la obligaci\u00f3n no ha sido cancelada. \u00bfQu\u00e9 ajuste por diferencia en cambio debe registrar el Asistente Contable?", opciones: ["Un cr\u00e9dito a la cuenta de Ingresos por Diferencia en Cambio (4210) por $2.000.000.", "Modificar retroactivamente el costo de la mercanc\u00eda ingresada al inventario subiendo su costo unitario en $200 COP por d\u00f3lar.", "Un d\u00e9bito a la cuenta de Gastos por Diferencia en Cambio (530525) por $2.000.000 y un cr\u00e9dito a Cuentas por Pagar Proveedores del Exterior (2210) por $2.000.000.", "No se realiza ning\u00fan registro hasta que se efect\u00fae el pago real en divisas mediante la cuenta de compensaci\u00f3n."], correcta: 2 },
            { id: 15, categoria: "Conciliaci\u00f3n Bancaria", pregunta: "\u00bfCu\u00e1l es el tratamiento contable y fiscal correcto respecto al Gravamen a los Movimientos Financieros (GMF / 4x1000) cobrado por las entidades bancarias seg\u00fan el Estatuto Tributario colombiano?", opciones: ["Se registra en la cuenta de gasto financiero (530505); fiscalmente es deducible el 50% del valor pagado en la declaraci\u00f3n del impuesto sobre la renta (Art. 115 E.T.).", "Se registra como un gasto financiero (530505), y el 100% del valor pagado es deducible en la declaraci\u00f3n de renta.", "Se registra como un activo por anticipo de impuestos (1355) para descontarlo del saldo a pagar de IVA.", "Se contabiliza como un menor valor de los rendimientos financieros abonados en cuenta."], correcta: 0 },
            { id: 16, categoria: "Cartera y Cuentas por Pagar", pregunta: "Al revisar el reporte de edades de cartera (Cuentas por Cobrar) para la gesti\u00f3n de cobro, \u00bfcu\u00e1l de las siguientes situaciones representa un riesgo inminente en la liquidez que exige reclasificaci\u00f3n o informe inmediato a la Jefatura de Contabilidad?", opciones: ["Una cartera corriente con 15 d\u00edas de expedici\u00f3n dentro del periodo de cr\u00e9dito pactado (30 d\u00edas).", "Facturas con vencimiento a 90 d\u00edas que cuentan con acuerdo de pago firmado y pagando cuotas de intereses.", "Saldos a favor en clientes (cartera en rojo) causados por retenciones practicadas en exceso por los clientes no cruzadas en contabilidad.", "Un volumen concentrado de facturas con mora superior a 120 d\u00edas sin garant\u00edas reales ni t\u00edtulos valores ejecutables."], correcta: 3 },
            { id: 17, categoria: "Excel Aplicado", pregunta: "Tienes un listado de 2.000 facturas exportadas del software contable en la Hoja1 (Columna A: NIT, Columna B: N\u00famero Factura, Columna C: Valor) y necesitas cruzar con el reporte de la DIAN en la Hoja2 para verificar si el valor coincide exactamente para el mismo NIT y Factura. \u00bfQu\u00e9 f\u00f3rmula combinada en Excel realiza esta verificaci\u00f3n de forma \u00f3ptima?", opciones: ["=BUSCARV(A2; Hoja2!A:C; 3; FALSO)", "=CONTAR.SI(Hoja2!A:A; A2)", "=SUMAR.SI.CONJUNTO(Hoja2!C:C; Hoja2!A:A; A2; Hoja2!B:B; B2)", "=CONCATENAR(A2; B2; C2)"], correcta: 2 },
            { id: 18, categoria: "Excel Aplicado", pregunta: "En el marco del cierre contable mensual, \u00bfcu\u00e1l es el orden l\u00f3gico estricto de ejecuci\u00f3n de tareas operativas que debe seguir el Asistente antes de la emisi\u00f3n de Balances de Prueba preliminares?", opciones: ["1. Elaborar estados financieros -> 2. Causar facturas de compra -> 3. Conciliar bancos -> 4. Liquidar n\u00f3mina.", "1. Causar facturas de venta y compra -> 2. Contabilizar n\u00f3mina y PILA -> 3. Realizar conciliaciones bancarias -> 4. Causar depreciaciones, diferidos y provisiones -> 5. Validar saldos e impuestos.", "1. Conciliar bancos -> 2. Cerrar cuentas de resultado -> 3. Causar compras -> 4. Generar certificados de retenci\u00f3n.", "1. Ajustar diferencia en cambio -> 2. Descargar extractos bancarios -> 3. Facturar a clientes -> 4. Transmitir n\u00f3mina electr\u00f3nica."], correcta: 1 },
            { id: 19, categoria: "Cartera y Cuentas por Pagar", pregunta: "Al realizar un arqueo de caja menor, el Asistente Contable detecta un faltante injustificado de $150.000 en custodia del responsable del fondo. \u00bfCu\u00e1l es el asiento contable correcto para proceder con el reembolso e igualar el fondo fijo?", opciones: ["Debitar la cuenta de Cuentas por Cobrar a Empleados (136530) por los $150.000, debitar las cuentas de costo/gasto con soporte v\u00e1lido, y acreditar Bancos (1110) por el valor total del reembolso.", "Debitar la cuenta de Gastos Diversos - Faltantes de caja (5195) y acreditar Caja Menor (110510).", "Acreditar Ingresos no operacionales (4295) y debitar Caja General (110505).", "No registrar el faltante y solicitar al custodio que complete el dinero en efectivo en el siguiente arqueo."], correcta: 0 },
            { id: 20, categoria: "Excel Aplicado", pregunta: "En Excel, necesitas categorizar las cuentas por cobrar autom\u00e1ticamente en rangos de morosidad ('Al d\u00eda', '1 a 30 d\u00edas', '31 a 60 d\u00edas', 'Mayor a 60 d\u00edas') seg\u00fan los d\u00edas de vencimiento calculados en la Columna D. \u00bfQu\u00e9 estructura l\u00f3gica funcional cumple con este objetivo correctamente?", opciones: ["=PROMEDIO.SI(D2:D100; \">0\")", "=BUSCARV(D2; {\"Al d\u00eda\"\\\"1 a 30 d\u00edas\"\\\"31 a 60 d\u00edas\"}; 1)", "=TEXTO(D2; \"dd/mm/aaaa\")", "=SI(D2<=0; \"Al d\u00eda\"; SI(D2<=30; \"1 a 30 d\u00edas\"; SI(D2<=60; \"31 a 60 d\u00edas\"; \"Mayor a 60 d\u00edas\")))"], correcta: 3 },
            { id: 21, categoria: "Conciliaci\u00f3n Bancaria", pregunta: "Al efectuar el cierre mensual de la cuenta del Impuesto a las Ventas (IVA 2408), la cuenta 240805 (IVA Generado) presenta un saldo cr\u00e9dito de $18.000.000 y la cuenta 240810 (IVA Descontable) un saldo d\u00e9bito de $12.000.000. \u00bfCu\u00e1l es el asiento de cancelaci\u00f3n y determinaci\u00f3n del saldo a pagar a la DIAN?", opciones: ["Debitar IVA Descontable (240810) por $12.000.000, acreditar IVA Generado (240805) por $18.000.000 y debitar Bancos por $6.000.000.", "Llevar los $6.000.000 directamente como costo en la cuenta 5115 Impuestos.", "Debitar IVA Generado (240805) por $18.000.000, acreditar IVA Descontable (240810) por $12.000.000 y acreditar Impuesto a las Ventas por Pagar (240890) por $6.000.000.", "Acreditar Cuentas por Cobrar Fiscales (135520) por $6.000.000 y debitar Ingresos."], correcta: 2 },
            { id: 22, categoria: "Normatividad Laboral", pregunta: "\u00bfEn qu\u00e9 cuenta del plan de cuentas / estructura NIIF debe registrarse el pago de las planillas de Seguridad Social (PILA) en la secci\u00f3n de las cotizaciones descontadas previamente a los empleados en la n\u00f3mina (Salud 4% y Pensi\u00f3n 4%)?", opciones: ["Se debitan de la cuenta de Pasivo / Retenciones y Aportes de N\u00f3mina (2370 / 2380) cancelando la obligaci\u00f3n causada en la n\u00f3mina.", "Se registran directamente como un Gasto Operacional de Administraci\u00f3n (5105).", "Se contabilizan como Costo de Ventas (6135).", "Se debitan de la cuenta de Reserva Legal en el Patrimonio (3305)."], correcta: 0 },
            { id: 23, categoria: "Normatividad Tributaria", pregunta: "Si un proveedor nos otorga un descuento comercial pie de factura (no condicionado) del 5% en la compra de mercanc\u00edas por $10.000.000, \u00bfcu\u00e1l es la base gravable para la liquidaci\u00f3n del IVA y las retenciones en la fuente?", opciones: ["La base es $10.000.000; el descuento se causa aparte como un ingreso financiero (4210).", "La base es $9.500.000 (valor neto comercial despu\u00e9s del descuento pie de factura).", "El IVA se calcula sobre $10.000.000 y la retenci\u00f3n en la fuente sobre $9.500.000.", "Los descuentos comerciales no afectan la base imponible por norma legal de la DIAN."], correcta: 1 },
            { id: 24, categoria: "\u00c9tica y Control Interno", pregunta: "Dentro de las buenas pr\u00e1cticas de control interno para la custodia de archivos y soporte de auditor\u00edas contables, \u00bfcu\u00e1l es el tiempo m\u00ednimo legal de conservaci\u00f3n de los libros de contabilidad, comprobantes de cuenta y soportes en Colombia (Art. 60 del C\u00f3digo de Comercio y Art. 632 del E.T.)?", opciones: ["1 a\u00f1o calendario coincidiendo con el periodo fiscal.", "6 meses desde la transmisi\u00f3n de la n\u00f3mina electr\u00f3nica.", "De forma indefinida exclusivamente en papel impreso firmado en f\u00edsico.", "M\u00ednimo 5 a\u00f1os contados a partir del 1 de enero del a\u00f1o siguiente al de su elaboraci\u00f3n o del vencimiento del t\u00e9rmino para declarar."], correcta: 3 }
        ]
    }
};

function analizarPerfilTecnico(respuestas) {
    var preguntas = PREGUNTAS.tecnico.preguntas;
    var total = preguntas.length;
    var aciertos = 0;
    var categorias = {};

    preguntas.forEach(function(preg, idx) {
        var resp = respuestas[idx];
        if (!categorias[preg.categoria]) {
            categorias[preg.categoria] = { label: preg.categoria, aciertos: 0, total: 0 };
        }
        categorias[preg.categoria].total++;
        if (resp === preg.correcta) {
            aciertos++;
            categorias[preg.categoria].aciertos++;
        }
    });

    var porcentaje = Math.round((aciertos / total) * 100);
    var veredicto;
    if (porcentaje >= 80) veredicto = 'Sobresaliente';
    else if (porcentaje >= 65) veredicto = 'Aceptable';
    else if (porcentaje >= 50) veredicto = 'Requiere Refuerzo';
    else veredicto = 'Insuficiente';

    Object.keys(categorias).forEach(function(cat) {
        categorias[cat].porcentaje = Math.round((categorias[cat].aciertos / categorias[cat].total) * 100);
    });

    var recomendacion;
    if (porcentaje >= 80) recomendacion = 'Excelente dominio t\u00e9cnico en contabilidad. Demuestra conocimiento s\u00f3lido en causaci\u00f3n, facturaci\u00f3n electr\u00f3nica, NIIF, normatividad tributaria, n\u00f3mina y conciliaci\u00f3n.';
    else if (porcentaje >= 65) recomendacion = 'Buen conocimiento t\u00e9cnico contable. Se recomienda reforzar las \u00e1reas con menor puntuaci\u00f3n mediante capacitaci\u00f3n espec\u00edfica.';
    else if (porcentaje >= 50) recomendacion = 'Conocimiento t\u00e9cnico b\u00e1sico. Requiere un plan de formaci\u00f3n estructurado en contabilidad, tributaria y herramientas digitales.';
    else recomendacion = 'Conocimiento t\u00e9cnico insuficiente para el rol. Se recomienda formaci\u00f3n integral antes de asumir responsabilidades contables.';

    return {
        puntaje: aciertos, total: total, porcentaje: porcentaje,
        veredicto: veredicto, categorias: categorias, recomendacion: recomendacion
    };
}