var PREGUNTAS = {
    disc: {
        nombre: "Perfil DISC - Evaluaci\u00f3n Comportamental Jefe Administrativo",
        descripcion: "Seleccione la opci\u00f3n que mejor lo describe. No hay respuestas correctas o incorrectas.",
        tiempo: 1200,
        preguntas: [
            { id: 1, dimensi: "D", pregunta: "Cuando un \u00e1rea incumple repetidamente sus metas administrativas, prefiero:", opcionA: "Intervenir directamente, exigir resultados y definir un plan correctivo", opcionB: "Analizar las causas con el equipo antes de tomar medidas", pesoA: 1, pesoB: 0 },
            { id: 2, dimensi: "D", pregunta: "Ante una decisi\u00f3n de recorte de presupuesto que afecta a mi equipo, yo:", opcionA: "Tomo la decisi\u00f3n y comunico los cambios con firmeza", opcionB: "Busco alternativas que minimicen el impacto en el personal", pesoA: 1, pesoB: 0 },
            { id: 3, dimensi: "D", pregunta: "Cuando gerencia pide acelerar un proyecto administrativo con recursos limitados:", opcionA: "Asumo el reto, reasigno prioridades y exijo resultados al equipo", opcionB: "Solicito m\u00e1s tiempo o recursos para no comprometer la calidad", pesoA: 1, pesoB: 0 },
            { id: 4, dimensi: "D", pregunta: "En una negociaci\u00f3n clave con un proveedor, mi estilo es:", opcionA: "Ser directo, plantear mis condiciones y cerrar el acuerdo r\u00e1pido", opcionB: "Explorar opciones y construir un acuerdo de mutuo beneficio", pesoA: 1, pesoB: 0 },
            { id: 5, dimensi: "D", pregunta: "Frente a un empleado con bajo desempe\u00f1o persistente, prefiero:", opcionA: "Aplicar el proceso disciplinario con claridad y firmeza", opcionB: "Buscar las causas y dar oportunidades de mejora primero", pesoA: 1, pesoB: 0 },
            { id: 6, dimensi: "D", pregunta: "Al liderar una reuni\u00f3n de seguimiento operativo, prefiero:", opcionA: "Dirigir la agenda, tomar decisiones y asignar responsables", opcionB: "Facilitar el debate y construir conclusiones en conjunto", pesoA: 1, pesoB: 0 },
            { id: 7, dimensi: "I", pregunta: "Para presentar los resultados del \u00e1rea a la gerencia general:", opcionA: "Preparo una presentaci\u00f3n persuasiva que destaque logros e impacto", opcionB: "Entrego un informe t\u00e9cnico detallado con indicadores precisos", pesoA: 1, pesoB: 0 },
            { id: 8, dimensi: "I", pregunta: "En la gesti\u00f3n del clima laboral, considero m\u00e1s efectivo:", opcionA: "Mantener comunicaci\u00f3n abierta y motivar al equipo con reconocimiento", opcionB: "Establecer pol\u00edticas claras y medir la satisfacci\u00f3n peri\u00f3dicamente", pesoA: 1, pesoB: 0 },
            { id: 9, dimensi: "I", pregunta: "Cuando debo convencer a gerencia de aprobar una inversi\u00f3n necesaria:", opcionA: "Presento el caso con datos y apelo a la visi\u00f3n de negocio", opcionB: "Entrego el an\u00e1lisis costo-beneficio por escrito y espero decisi\u00f3n", pesoA: 1, pesoB: 0 },
            { id: 10, dimensi: "I", pregunta: "En procesos de selecci\u00f3n de personal, prefiero:", opcionA: "Entrevistar candidatos y evaluar el ajuste cultural y motivacional", opcionB: "Basarme en pruebas t\u00e9cnicas y verificaci\u00f3n de competencias", pesoA: 1, pesoB: 0 },
            { id: 11, dimensi: "I", pregunta: "Cuando hay un conflicto entre dos \u00e1reas de la empresa, mi rol es:", opcionA: "Mediar, escuchar ambas partes y facilitar un acuerdo", opcionB: "Emitir una directriz clara con base en las pol\u00edticas establecidas", pesoA: 1, pesoB: 0 },
            { id: 12, dimensi: "I", pregunta: "Al recibir cr\u00edticas del equipo sobre mi gesti\u00f3n, prefiero:", opcionA: "Dialogar abiertamente y ajustar lo que sea razonable", opcionB: "Analizar si las cr\u00edticas tienen fundamento t\u00e9cnico antes de actuar", pesoA: 1, pesoB: 0 },
            { id: 13, dimensi: "S", pregunta: "En el monitoreo mensual de los KPIs del \u00e1rea:", opcionA: "Mantengo una rutina disciplinada de revisi\u00f3n y an\u00e1lisis de variaciones", opcionB: "Reviso cuando hay desviaciones significativas que lo ameriten", pesoA: 1, pesoB: 0 },
            { id: 14, dimensi: "S", pregunta: "Ante cambios en la legislaci\u00f3n laboral que afectan la operaci\u00f3n:", opcionA: "Actualizo los procesos con un sistema de control de cambios peri\u00f3dico", opcionB: "Ajusto lo necesario seg\u00fan la urgencia de cada cambio", pesoA: 1, pesoB: 0 },
            { id: 15, dimensi: "S", pregunta: "En el seguimiento del presupuesto administrativo, prefiero:", opcionA: "Revisarlo peri\u00f3dicamente con disciplina y anticipar desviaciones", opcionB: "Revisarlo al cierre de cada periodo o ante alertas", pesoA: 1, pesoB: 0 },
            { id: 16, dimensi: "S", pregunta: "En la implementaci\u00f3n del Sistema de Gesti\u00f3n de Calidad (SIG):", opcionA: "Seguir met\u00f3dicamente cada fase del plan de implementaci\u00f3n", opcionB: "Ajustar el plan seg\u00fan las necesidades reales de la operaci\u00f3n", pesoA: 1, pesoB: 0 },
            { id: 17, dimensi: "S", pregunta: "Cuando el \u00e1rea opera de forma estable y sin novedades:", opcionA: "Aprovecho para fortalecer procesos, documentaci\u00f3n y mejora continua", opcionB: "Busco nuevos proyectos e innovaciones para el \u00e1rea", pesoA: 1, pesoB: 0 },
            { id: 18, dimensi: "S", pregunta: "En el seguimiento de los planes de acci\u00f3n del \u00e1rea, prefiero:", opcionA: "Dar seguimiento met\u00f3dico a cada tarea hasta su cierre completo", opcionB: "Priorizar las tareas cr\u00edticas y delegar las dem\u00e1s", pesoA: 1, pesoB: 0 },
            { id: 19, dimensi: "C", pregunta: "Al construir el informe ejecutivo mensual para gerencia:", opcionA: "Verifico cada cifra, indicador y conclusi\u00f3n antes de presentarlo", opcionB: "Consolido la informaci\u00f3n clave y destaco los aspectos m\u00e1s relevantes", pesoA: 1, pesoB: 0 },
            { id: 20, dimensi: "C", pregunta: "Frente a un nuevo requisito legal laboral que aplica a la empresa:", opcionA: "Estudio la norma a fondo y verifico el cumplimiento de cada art\u00edculo", opcionB: "Identifico los aspectos principales y ajusto lo necesario", pesoA: 1, pesoB: 0 },
            { id: 21, dimensi: "C", pregunta: "Al analizar los indicadores del \u00e1rea antes de tomar una decisi\u00f3n:", opcionA: "Cruzo datos de m\u00faltiples fuentes y valido su consistencia", opcionB: "Me baso en los datos principales y mi experiencia", pesoA: 1, pesoB: 0 },
            { id: 22, dimensi: "C", pregunta: "En el manejo de informaci\u00f3n confidencial de n\u00f3mina y personal:", opcionA: "Sigo protocolos estrictos de confidencialidad y control de acceso", opcionB: "Conf\u00edo en la discreci\u00f3n del equipo y los sistemas establecidos", pesoA: 1, pesoB: 0 },
            { id: 23, dimensi: "C", pregunta: "Al revisar un contrato o acuerdo con proveedores:", opcionA: "Leo cada cl\u00e1usula y verifico el cumplimiento de las condiciones", opcionB: "Reviso los puntos principales y las condiciones comerciales", pesoA: 1, pesoB: 0 },
            { id: 24, dimensi: "C", pregunta: "Cuando debo decidir sobre una inversi\u00f3n tecnol\u00f3gica para el \u00e1rea:", opcionA: "Preparo un an\u00e1lisis t\u00e9cnico y financiero detallado antes de decidir", opcionB: "Eval\u00fao las opciones principales y recomiendo la m\u00e1s adecuada", pesoA: 1, pesoB: 0 }
        ]
    },
    tecnico: {
        nombre: "Evaluaci\u00f3n T\u00e9cnica - Jefe Administrativo",
        descripcion: "Eval\u00faa tus conocimientos en legislaci\u00f3n laboral, RRHH, indicadores, presupuesto, SIG, herramientas digitales y gesti\u00f3n de proyectos.",
        tiempo: 1440,
        preguntas: [
            { id: 1, categoria: "Legislaci\u00f3n Laboral", pregunta: "En relaci\u00f3n con la suspensi\u00f3n del contrato de trabajo por incapacidad de origen com\u00fan superior a 180 d\u00edas en Colombia, \u00bfcu\u00e1l es el procedimiento legal y la obligaci\u00f3n del empleador respecto a las cotizaciones al Sistema General de Seguridad Social?", opciones: ["El contrato se suspende autom\u00e1ticamente, cesando la obligaci\u00f3n de pagar salarios y la cotizaci\u00f3n a EPS y Pensi\u00f3n por parte del empleador.", "Se debe solicitar autorizaci\u00f3n inmediata al Ministerio del Trabajo para dar por terminado el contrato con indemnizaci\u00f3n.", "El contrato subsiste; el empleador no paga salario, pero mantiene la obligaci\u00f3n de aportar a la EPS y a Pensi\u00f3n sobre el IBC correspondiente al auxilio por incapacidad.", "El empleador contin\u00faa pagando el salario completo y realiza el cobro directo mediante cartera a la Administradora del Fondo de Pensiones (AFP)."], correcta: 2 },
            { id: 2, categoria: "Legislaci\u00f3n Laboral", pregunta: "Durante un proceso disciplinario interno, la empresa detecta una falta grave. Se le entrega al trabajador la citaci\u00f3n a descargos con 2 horas de anticipaci\u00f3n. El trabajador asiste, acepta la falta y es despedido. \u00bfQu\u00e9 vicio de nulidad se presenta seg\u00fan la Sentencia C-593/14 de la Corte Constitucional?", opciones: ["Violaci\u00f3n al debido proceso por vulneraci\u00f3n del derecho a la defensa al no otorgar un t\u00e9rmino razonable para preparar las pruebas y la defensa.", "Ninguno, ya que la confesi\u00f3n del trabajador convalida la inmediatez del procedimiento.", "Vulneraci\u00f3n al principio de tipicidad, al no estar la falta descrita textualmente en el C\u00f3digo Sustantivo del Trabajo.", "Falta de competencia, dado que las faltas graves solo pueden ser sancionadas por un juez laboral."], correcta: 0 },
            { id: 3, categoria: "Legislaci\u00f3n Laboral", pregunta: "Un trabajador goza de ret\u00e9n social o fuero de salud sin p\u00e9rdida de capacidad laboral calificada (PCL) formal por junta, pero cuenta con recomendaciones m\u00e9dicas vigentes por patolog\u00eda cr\u00f3nica. La empresa decide despedirlo con pago de indemnizaci\u00f3n sin autorizaci\u00f3n del Ministerio del Trabajo. \u00bfCu\u00e1l es la consecuencia jur\u00eddica probable?", opciones: ["El despido es legalmente v\u00e1lido siempre que se pague la indemnizaci\u00f3n del Art. 64 del CST.", "Se genera una indemnizaci\u00f3n adicional de 180 d\u00edas de salario (Ley 361/97), pero no procede el reintegro.", "El pago obligatorio de una pensi\u00f3n de invalidez asumida directamente por el empleador.", "Ineficacia del despido, ordenando el reintegro inmediato del trabajador, el pago de salarios/prestaciones dejados de percibir y la sanci\u00f3n de 180 d\u00edas de salario."], correcta: 3 },
            { id: 4, categoria: "Legislaci\u00f3n Laboral", pregunta: "Al aplicar la figura del Ius Variandi (modificaci\u00f3n sustancial de las condiciones de trabajo) para cambiar la sede laboral o el horario de un colaborador, \u00bfcu\u00e1l es el l\u00edmite legal infranqueable para el empleador?", opciones: ["Que el trabajador lleve m\u00e1s de 5 a\u00f1os en el mismo puesto de trabajo.", "Que la medida no cause un perjuicio moral o patrimonial grave (desmejoramiento) al trabajador ni a su n\u00facleo familiar.", "El consentimiento expreso y por escrito del sindicato de la empresa.", "Que la modificaci\u00f3n no altere en m\u00e1s del 10% el volumen de funciones del cargo."], correcta: 1 },
            { id: 5, categoria: "Gesti\u00f3n de RRHH", pregunta: "En el c\u00e1lculo de la rotaci\u00f3n de personal (Turnover Rate), si una empresa tiene 120 empleados al inicio del a\u00f1o, 140 al final, y durante el periodo salieron 30 personas (20 por renuncia voluntaria y 10 por despido con justa causa), \u00bfcu\u00e1l es la tasa de rotaci\u00f3n voluntaria anual utilizando el promedio de personal?", opciones: ["23.07%", "14.28%", "15.38%", "25.00%"], correcta: 2 },
            { id: 6, categoria: "Legislaci\u00f3n Laboral", pregunta: "\u00bfCu\u00e1l es la diferencia fundamental entre el auxilio de incapacidad pagado por la EPS entre el d\u00eda 3 y el d\u00eda 540 de una enfermedad general?", opciones: ["Del d\u00eda 3 al 90 la EPS reconoce el 66.67% del IBC; del d\u00eda 91 al 540 reconoce el 50% (sin ser inferior al SMMLV).", "Del d\u00eda 3 al 60 lo paga el empleador al 100%; del d\u00eda 61 al 540 lo paga la EPS al 50%.", "Del d\u00eda 3 al 180 lo asume la EPS; a partir del d\u00eda 181 la obligaci\u00f3n se traslada autom\u00e1ticamente a la ARL.", "No hay diferencia; la EPS asume el 100% del IBC desde el d\u00eda 3 hasta la calificaci\u00f3n de invalidez."], correcta: 0 },
            { id: 7, categoria: "SIG y Calidad", pregunta: "Seg\u00fan la norma ISO 9001:2015, \u00bfcu\u00e1l es la diferencia conceptual entre una 'Correcci\u00f3n' y una 'Acci\u00f3n Correctiva'?", opciones: ["La correcci\u00f3n elimina la causa ra\u00edz; la acci\u00f3n preventiva elimina el efecto no deseado.", "La correcci\u00f3n elimina una no conformidad detectada (trata el s\u00edntoma); la acci\u00f3n correctiva elimina la causa ra\u00edz para prevenir su recurrencia.", "La correcci\u00f3n aplica solo para auditor\u00edas externas; la acci\u00f3n correctiva aplica para hallazgos internos.", "Ambas son sin\u00f3nimos normativos aplicados al control de cambios en la gesti\u00f3n de proyectos."], correcta: 1 },
            { id: 8, categoria: "SIG y Calidad", pregunta: "Si durante una auditor\u00eda interna del SIG se detecta que no se han realizado los mantenimientos preventivos del equipo de c\u00f3mputo cr\u00edtico, afectando el proceso de compras, \u00bfc\u00f3mo debe gestionarse la causa ra\u00edz utilizando la metodolog\u00eda de los 5 Porqu\u00e9s?", opciones: ["Detener el an\u00e1lisis en la causa inmediata: 'El t\u00e9cnico no ejecut\u00f3 la rutina'.", "Redactar una acci\u00f3n preventiva para el ciclo de auditor\u00eda del a\u00f1o siguiente.", "Eliminar el indicador de mantenimiento preventivo para evitar el incumplimiento de la norma.", "Escalar la falla hasta identificar brechas en la asignaci\u00f3n de presupuesto, la falta de controles en la programaci\u00f3n del proceso o vac\u00edos en el procedimiento."], correcta: 3 },
            { id: 9, categoria: "SIG y Calidad", pregunta: "De acuerdo con el numeral 6.3 de la ISO 9001:2015 ('Planificaci\u00f3n de los cambios'), al implementar un nuevo software de gesti\u00f3n de procesos en la empresa, el SIG exige priorizar:", opciones: ["La evaluaci\u00f3n del prop\u00f3sito del cambio, sus consecuencias, la integridad del SIG, la disponibilidad de recursos y la asignaci\u00f3n de responsabilidades.", "La contrataci\u00f3n inmediata de auditores externos para certificar el cambio.", "La actualizaci\u00f3n exclusiva del manual de calidad impreso del \u00e1rea de TI.", "La interrupci\u00f3n de todos los procesos operativos hasta completar la migraci\u00f3n de datos."], correcta: 0 },
            { id: 10, categoria: "SIG y Calidad", pregunta: "\u00bfCu\u00e1l de los siguientes indicadores eval\u00faa formalmente la Eficacia de un procedimiento dentro del SIG?", opciones: ["(Costo total real del proceso / Costo presupuestado) * 100", "(N\u00famero de actividades ejecutadas en tiempo / Total de recursos consumidos) * 100", "(Resultados / Metas alcanzadas frente a las metas planificadas del proceso) * 100", "Horas hombre invertidas por cada solicitud administrativa procesada."], correcta: 2 },
            { id: 11, categoria: "Indicadores y Finanzas", pregunta: "Al construir la bater\u00eda de KPIs del \u00e1rea administrativa, \u00bfcu\u00e1l es la principal caracter\u00edstica de un indicador de resultado (Lagging Indicator) frente a uno de proceso (Leading Indicator)?", opciones: ["El Lagging mide las acciones preventivas en tiempo real; el Leading mide eventos pasados.", "El Lagging mide el resultado final alcanzado (ej. Variaci\u00f3n presupuestal anual); el Leading mide las variables de entrada que predicen el desempe\u00f1o futuro (ej. % Cumplimiento del plan de compras mensual).", "El Lagging solo se aplica a finanzas; el Leading solo se aplica a recursos humanos.", "El Lagging es un indicador cualitativo; el Leading es estrictamente cuantitativo."], correcta: 1 },
            { id: 12, categoria: "Indicadores y Finanzas", pregunta: "En un an\u00e1lisis de varianza presupuestal, el rubro de insumos de oficina present\u00f3 una variaci\u00f3n desfavorable en dinero del 18%. El an\u00e1lisis detallado revela que el volumen consumido baj\u00f3 un 5%, pero el precio unitario negociado subi\u00f3 un 24.2%. \u00bfCu\u00e1l debe ser la decisi\u00f3n estrat\u00e9gica del Jefe Administrativo basada en estos datos?", opciones: ["Sancionar al personal por consumo desmedido de insumos.", "Recortar el personal del \u00e1rea de compras por falta de control de inventario.", "Aumentar el presupuesto del pr\u00f3ximo a\u00f1o en un 18% sin renegociar con proveedores.", "Revisar la gesti\u00f3n de la cadena de suministro/proveedores e iniciar negociaci\u00f3n de tarifas o sustituci\u00f3n de insumos, reconociendo que la eficiencia operativa interna mejor\u00f3."], correcta: 3 },
            { id: 13, categoria: "Indicadores y Finanzas", pregunta: "En el Balanced Scorecard (Cuadro de Mando Integral), la optimizaci\u00f3n del tiempo de respuesta en las compras administrativas y el soporte tecnol\u00f3gico impactan directamente en la perspectiva de:", opciones: ["Procesos Internos, generando un efecto en cadena sobre la eficiencia financiera.", "Aprendizaje y Crecimiento.", "Clientes (externos exclusivamente).", "Sustentabilidad y Medio Ambiente."], correcta: 0 },
            { id: 14, categoria: "Indicadores y Finanzas", pregunta: "Al evaluar una inversi\u00f3n en equipos inform\u00e1ticos utilizando el indicador Valor Presente Neto (VPN), si a una tasa de descuento del 12% el VPN es exactamente igual a 0, esto significa que:", opciones: ["El proyecto genera p\u00e9rdidas financieras netas para la empresa.", "El proyecto recuperar\u00e1 la inversi\u00f3n en la mitad del tiempo esperado.", "La rentabilidad del proyecto es exactamente igual a la tasa de descuento requerida (TIR = 12%).", "La decisi\u00f3n t\u00e9cnica correcta es rechazar el proyecto por falta de liquidez."], correcta: 2 },
            { id: 15, categoria: "Toma de Decisiones", pregunta: "\u00bfCu\u00e1l es el sesgo cognitivo en la toma de decisiones que ocurre cuando un administrador mantiene un proyecto de software ineficiente \u00fanicamente porque la empresa ya ha invertido $50 millones de pesos en \u00e9l?", opciones: ["Sesgo de confirmaci\u00f3n.", "Falacia del costo hundido (Sunk Cost Fallacy).", "Sesgo de disponibilidad.", "Sesgo de anclaje."], correcta: 1 },
            { id: 16, categoria: "Herramientas Digitales", pregunta: "En Excel, necesitas buscar el sueldo de un empleado buscando simult\u00e1neamente su 'C\u00e9dula' (Columna A) y su 'Sede' (Columna B). \u00bfCu\u00e1l de las siguientes f\u00f3rmulas realiza la b\u00fasqueda matricial de manera m\u00e1s limpia y eficiente sin modificar el orden de las columnas?", opciones: ["=BUSCARV(A2&B2; A:D; 4; FALSO)", "=INDICE(D2:D100; COINCIDIR(E2; A2:A100; 0))", "=CONTAR.SI.CONJUNTO(A2:A100; E2; B2:B100; F2)", "=BUSCARX(1; (A2:A100=E2)*(B2:B100=F2); D2:D100)"], correcta: 3 },
            { id: 17, categoria: "Herramientas Digitales", pregunta: "En un modelo de datos en Excel (Power Pivot), \u00bfcu\u00e1l es la ventaja cr\u00edtica de crear una medida expl\u00edcita mediante un campo calculado en DAX frente a un campo calculado tradicional en una Tabla Din\u00e1mica?", opciones: ["Las medidas impl\u00edcitas eliminan la necesidad de crear relaciones entre tablas.", "DAX solo funciona si los archivos est\u00e1n guardados en la nube de Google.", "Las medidas expl\u00edcitas en DAX permiten evaluar el contexto de filtro (Filter Context) din\u00e1mico sobre millones de filas optimizando la memoria RAM.", "Las tablas din\u00e1micas tradicionales no permiten sumar valores num\u00e9ricos."], correcta: 2 },
            { id: 18, categoria: "Herramientas Digitales", pregunta: "En la administraci\u00f3n de Google Workspace corporativo, \u00bfcu\u00e1l es la diferencia principal en t\u00e9rminos de gobernanza y propiedad de los datos entre 'Mi Unidad' y una 'Unidad Compartida' (Shared Drive)?", opciones: ["En 'Unidad Compartida' la organizaci\u00f3n es due\u00f1a de los archivos; si el usuario creador es eliminado de la empresa, los archivos permanecen intactos en la unidad.", "En 'Mi Unidad' los archivos pertenecen a la empresa; en 'Unidad Compartida' pertenecen a la cuenta personal del creador.", "'Mi Unidad' no permite compartir archivos con usuarios externos al dominio.", "Las 'Unidades Compartidas' solo aceptan archivos creados en formato Microsoft Office."], correcta: 0 },
            { id: 19, categoria: "Protecci\u00f3n de Datos", pregunta: "Seg\u00fan la Ley 1581 de 2012 (Habeas Data en Colombia), si el \u00e1rea de Administraci\u00f3n almacena datos personales de candidatos y empleados en carpetas compartidas de la nube, \u00bfcu\u00e1l es una exigencia legal prioritaria para la empresa como 'Responsable del Tratamiento'?", opciones: ["Publicar las hojas de vida en la p\u00e1gina web corporativa para garantizar transparencia.", "Contar con la autorizaci\u00f3n previa, expresa e informada del titular y registrar las bases de datos ante la RNBD (Superintendencia de Industria y Comercio) si cumple los topes de activos.", "Guardar las hojas de vida de candidatos rechazados por un periodo m\u00ednimo de 20 a\u00f1os sin su consentimiento.", "Encriptar las carpetas \u00fanicamente mediante claves personales e intransferibles del auxiliar de RRHH."], correcta: 1 },
            { id: 20, categoria: "Compras y Negociaci\u00f3n", pregunta: "Al aplicar el concepto de Costo Total de Propiedad (TCO - Total Cost of Ownership) en la compra de una flota de impresoras corporativas, \u00bfcu\u00e1l de los siguientes an\u00e1lisis es el correcto?", opciones: ["Elegir la impresora con el precio de compra inicial m\u00e1s bajo del mercado.", "Comparar \u00fanicamente la garant\u00eda extendida ofrecida contra la depreciaci\u00f3n contable anual.", "Evaluar \u00fanicamente el costo del servicio de env\u00edo e instalaci\u00f3n ofrecido por el proveedor.", "Evaluar el precio de adquisici\u00f3n + costo de insumos (toner/papel) + mantenimiento preventivo/correctivo + consumo energ\u00e9tico + costo de disposici\u00f3n final durante el ciclo de vida."], correcta: 3 },
            { id: 21, categoria: "Compras y Negociaci\u00f3n", pregunta: "En la Matriz de Kraljic para la segmentaci\u00f3n de compras, \u00bfd\u00f3nde se ubicar\u00eda la adquisici\u00f3n de papeler\u00eda e insumos b\u00e1sicos de oficina para una empresa de servicios, y cu\u00e1l debe ser la estrategia de gesti\u00f3n?", opciones: ["Productos Rutinarios (No cr\u00edticos) \u2014 Simplificaci\u00f3n de procesos, estandarizaci\u00f3n y automatizaci\u00f3n de pedidos.", "Productos Cuello de Botella \u2014 Asegurar suministro sin importar costo.", "Productos Estrat\u00e9gicos \u2014 Alianzas a largo plazo.", "Productos Palanca \u2014 Licitaci\u00f3n agresiva constante."], correcta: 0 },
            { id: 22, categoria: "Indicadores y Finanzas", pregunta: "En la formulaci\u00f3n del presupuesto del \u00e1rea administrativa, \u00bfcu\u00e1l es la diferencia contable y operativa entre una erogaci\u00f3n clasificada como CAPEX y una como OPEX?", opciones: ["CAPEX representa gastos operativos recurrentes (ej. arriendo, servicios); OPEX representa activos fijos de inversi\u00f3n de largo plazo (ej. compra de servidor).", "CAPEX se deduce al 100% del impuesto de renta en el mismo mes del pago; OPEX no es deducible.", "CAPEX son inversiones en bienes que se capitalizan y deprecian en el tiempo; OPEX son los gastos operativos diarios necesarios para mantener el negocio en marcha.", "CAPEX aplica \u00fanicamente para contrataci\u00f3n de personal; OPEX para compra de insumos f\u00edsicos."], correcta: 2 },
            { id: 23, categoria: "Proyectos y Cambio", pregunta: "En el m\u00e9todo de la Ruta Cr\u00edtica (CPM) de un proyecto administrativo de remodelaci\u00f3n de oficinas, si una actividad que NO est\u00e1 en la ruta cr\u00edtica sufre un retraso menor a su 'Holgura Total', \u00bfqu\u00e9 impacto tiene en la fecha final de entrega del proyecto?", opciones: ["El proyecto se retrasa exactamente el mismo n\u00famero de d\u00edas que la actividad.", "El proyecto no sufre ning\u00fan retraso en su fecha de finalizaci\u00f3n global.", "La ruta cr\u00edtica cambia autom\u00e1ticamente a la actividad retrasada de inmediato.", "El presupuesto del proyecto debe incrementarse un 10% por penalidad."], correcta: 1 },
            { id: 24, categoria: "Proyectos y Cambio", pregunta: "Al implementar un nuevo sistema ERP en el \u00e1rea administrativa, el modelo de gesti\u00f3n del cambio ADKAR se\u00f1ala que antes de capacitar a los empleados en el uso t\u00e9cnico del software (Conocimiento / Knowledge), la gerencia debi\u00f3 haber asegurado:", opciones: ["El pago de una bonificaci\u00f3n econ\u00f3mica a todos los usuarios del sistema.", "La liquidaci\u00f3n formal de los contratos del personal no adaptado.", "La auditor\u00eda de calidad ISO 9001 sobre la interfaz del software.", "La Conciencia (Awareness) de la necesidad del cambio y el Deseo (Desire) de participar y apoyarlo."], correcta: 3 }
        ]
    }
};

function analizarPerfilTecnico(respuestas) {
    var preguntas = PREGUNTAS.tecnico.preguntas;
    var total = preguntas.length;
    var aciertos = 0;
    var categorias = {};

    preguntas.forEach(function(preg, idx) {
        var resp = respuestas[idx];
        if (!categorias[preg.categoria]) {
            categorias[preg.categoria] = { label: preg.categoria, aciertos: 0, total: 0 };
        }
        categorias[preg.categoria].total++;
        if (resp === preg.correcta) {
            aciertos++;
            categorias[preg.categoria].aciertos++;
        }
    });

    var porcentaje = Math.round((aciertos / total) * 100);
    var veredicto;
    if (porcentaje >= 80) veredicto = 'Sobresaliente';
    else if (porcentaje >= 65) veredicto = 'Aceptable';
    else if (porcentaje >= 50) veredicto = 'Requiere Refuerzo';
    else veredicto = 'Insuficiente';

    Object.keys(categorias).forEach(function(cat) {
        categorias[cat].porcentaje = Math.round((categorias[cat].aciertos / categorias[cat].total) * 100);
    });

    var recomendacion;
    if (porcentaje >= 80) recomendacion = 'Excelente dominio t\u00e9cnico en gesti\u00f3n administrativa. Demuestra conocimiento s\u00f3lido en legislaci\u00f3n laboral, RRHH, indicadores, presupuesto y sistemas de gesti\u00f3n.';
    else if (porcentaje >= 65) recomendacion = 'Buen conocimiento t\u00e9cnico. Se recomienda reforzar las \u00e1reas con menor puntuaci\u00f3n mediante formaci\u00f3n espec\u00edfica.';
    else if (porcentaje >= 50) recomendacion = 'Conocimiento t\u00e9cnico b\u00e1sico. Requiere formaci\u00f3n estructurada en gesti\u00f3n administrativa y financiera.';
    else recomendacion = 'Conocimiento t\u00e9cnico insuficiente para el rol directivo. Se recomienda formaci\u00f3n integral antes de asumir la jefatura.';

    return {
        puntaje: aciertos, total: total, porcentaje: porcentaje,
        veredicto: veredicto, categorias: categorias, recomendacion: recomendacion
    };
}
